- repository: autowarefoundation/autoware
  files:
    - source: .github/dependabot.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .markdownlint.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml

- repository: autowarefoundation/autoware-github-actions
  files:
    - source: .github/workflows/actions-tagger.yaml
    - source: .github/workflows/github-release.yaml
